Cover get_case_history endpoint
GetDutchie/test_rail_dart pull request #10
Opened 2022-02-01 14:42 UTC by ervuks

Cover get_case_history endpoint

2022-02-01 16:48 UTC, tshedor reviewed
Would you mind adding this to the README and example file as well please?

2022-02-01 16:48 UTC, tshedor commented on lib/test_case_history.dart
> +    createdOn = DateTime.fromMillisecondsSinceEpoch(json['created_on']);
```suggestion
    var createdOn = DateTime.fromMillisecondsSinceEpoch(json['created_on']);
```

2022-02-01 16:48 UTC, tshedor commented on lib/test_case_history.dart
> +      oldValue: json['old_value'],
Alpha

2022-02-01 16:48 UTC, tshedor commented on test/test_case_test.dart
> +    test('#getHistory', () async {
This should be in its own test file (`test/test_case_history_test.dart`) and be annotated `.get` instead

2022-02-04 17:56 UTC, Victorrent approved these changes

2022-02-04 17:58 UTC, Victorrent commented on lib/test_case_history.dart
> +    this.typeId,
```suggestion
    this.field,
    this.label,
    this.newText,
    this.newValue,
    this.oldText,
    this.oldValue,
    this.options,
    this.typeId,
```

2022-02-04 20:23 UTC, Josiassejod1 commented on test/test_case_history_test.dart
> +  group('TestCase', () {
```suggestion
  group('TestCaseHistory', () {
```

2022-02-07 19:32 UTC, tshedor requested changes

2022-02-07 19:32 UTC, tshedor commented on example/main.dart
> -  await newRun.update(
Should all of this really be deleted? I think we still want this example code.

2022-02-10 15:45 UTC, tshedor approved these changes

2022-04-03 22:49 UTC, merged