Implementation of get_runs endpoint
GetDutchie/test_rail_dart pull request #4
Opened 2022-01-10 12:40 UTC by ervuks

[get_runs](https://www.gurock.com/testrail/docs/api/reference/runs/#getruns) endpoint implementation.

2022-01-10 17:56 UTC, tshedor requested changes

2022-01-10 17:56 UTC, tshedor commented on test/test_run_test.dart
> +    test('.getRuns', () async {
```suggestion
    test('.getAll', () async {
```

2022-01-10 17:56 UTC, tshedor commented on lib/test_runs.dart
> +  factory Links.fromJson(Map<String, dynamic> json) {
```suggestion
class _Links {
  final String? next;
  final String? prev;

  _Links({
    this.next,
    this.prev,
  });

  factory _Links.fromJson(Map<String, dynamic> json) {
```

2022-01-10 19:36 UTC, tshedor approved these changes

2022-01-11 01:00 UTC, Josiassejod1 approved these changes

2022-01-11 17:18 UTC, merged